version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: patient-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  patients:
    build: .
    container_name: ${SERVICE_NAME}
    depends_on:
      - db
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    env_file:
      - .env
      
volumes:
  postgres-data: